### ISSUE TITLE
Tracking: non-published external dependencies

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#1037]
This ticket tracks dependencies, which prevent us from publishing substrate on crates.io because they are referencing unpublished external dependencies, either because they are not yet released themselves or because we are depending on forks that aren't mainline.

- [x] [libp2p and its depedencies](https://github.com/libp2p/rust-libp2p/issues/593) in `substrate-network-libp2p <- substrate-network`
- [x] integer-sqrt v0.1.0 (https://github.com/paritytech/integer-sqrt-rs.git#886e9cb9) in `sr-primitives`
   - https://github.com/derekdreery/integer-sqrt-rs/pull/7
- [x] trie : #1520 
- [x] jsonrpc:
    - [-] jsonrpc-core v9.0.0 (https://github.com/paritytech/jsonrpc.git#207a277b) `substrate-rpc`
    - [-] jsonrpc-macros v9.0.0 (https://github.com/paritytech/jsonrpc.git#207a277b)  `substrate-rpc`
    - [-] jsonrpc-pubsub v9.0.0 (https://github.com/paritytech/jsonrpc.git#207a277b)  `substrate-rpc`; `substrate-rpc-servers`
    - [-] jsonrpc-http-server v9.0.0 (https://github.com/paritytech/jsonrpc.git#207a277b) in `substrate-rpc-servers`
    - [x] jsonrpc-ws-server v9.0.0 (https://github.com/paritytech/jsonrpc.git#207a277b) in `substrate-rpc-servers`
         - [x] ws v0.7.5 (https://github.com/tomusdrw/ws-rs#f12d19c4) , waits on https://github.com/housleyjk/ws-rs/pull/252 

_Legend_: [x] Done; [ ] Open; [-] Released on crates, not yet updated here.

----

Generated with the help of `cargo tree --all-targets --all-features --no-indent | grep github`

**Comment by gnunicorn** [comment]
libp2p's dependencies are released now, however, we still depend on it via github links.

**Comment by gnunicorn** [comment]
it appears many (but not all) of the json-rpc crates have been published on crates.io by now, but not the changeset we are currently referencing.

**Comment by tomaka** [comment]
#1386 uses libp2p from crates.io.

**Comment by bkchr** [comment]
Fixed by: https://github.com/paritytech/substrate/pull/1679
