### ISSUE TITLE
Benchmarking Roadmap 2022 (Tracking Issue)

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#10530]
In 2022, we should prioritize the next wave of benchmarking and optimization for Substrate / Polkadot.

## Goals

* improve transaction density / throughput in blocks.
* improve developer quality of life for benchmarks

## Developer Quality of Life

- [ ] Migration existing `benchmarks!` macro to attribute macros
- [ ] Improve `list_benchmark`, `add_benchmark` to remove redundancy and manual management (maybe a meta macro for the definition)
- [ ] Add a flag to FRAME storage for "keeping a storage in memory" from block to block, automatically populates whitelist, and remove the need for manual whitelist declaration.

## Improve Throughput

- [ ] Switch from RocksDB to ParityDB (Q1 2022)
- [ ] Reassess previous assumptions (block overhead, transaction overhead, etc...)
- [ ]  New reference hardware for benchmarking the runtime.
    - [ ] Rerun benchmarks for this hardware.
    - [ ] Migration plan for community to switch to this hardware.

## Improve Accuracy

- [ ] Complete work for PoV benchmarking.
- [ ] Track memory read / writes in addition to DB read / writes.
- [ ] Dual weight limits for Collators on Parachain Network and Validators on Polkadot Network
- [ ] Dynamic Storage Weights (measuring DB reads / writes impact dynamically based on worst case encoding size)
