### ISSUE TITLE
Add the output of a static html page with benchmark results in numbers and charts to the benchmark-cli

### ISSUE THREAD

**Issue by hirschenberger** [paritytech/substrate#10996]
### Task:
I'd like to add the output of a static html page with benchmark results in numbers and charts to the benchmark-cli.

I discussed that with @shawntabrizi some time ago and he hinted me to a webpage he created that displays benchmark results in a nice way. That can be used as starter for implementing that feature:

https://www.shawntabrizi.com/substrate-graph-benchmarks/?p=democracy&e=on_initialize_base

and the code: 

https://github.com/shawntabrizi/substrate-graph-benchmarks

I saw that @ggwpez is now also working on the benchmarking framework, so I'd also like to know your opinion.

### Steps:
- [ ] Add a `--html-output` flag to the benchmarking cli
- [ ] Add a handlebars-template for the HTML output
- [ ] Add a `html_writer.rs` which generates the HTML output from the benchmak results and the template file.

### Questions:
- Is it ok to load external JS libs from the HTML file or should it be capable to be viewed offline?
- Any feature wishes?

**Comment by hirschenberger** [comment]
Ok, np. I have not put so much effort into this yet. 

I also thought about extending and using the JSON data, that makes sense, also more convenient to develop.

I can't find the `susbtrate-graph-benchmarks` repo, is it public?

**Comment by ggwpez** [comment]
Many thanks for your initiative!  

I also think it makes more sense to post-process the JSON outside of the node.  
Either extending @shawntabrizi website or creating a new web-interactive tool which just consumes the JSON.  

> ...and move on to see where else I can help in rust.

@shawntabrizi maybe do you know something?
