### ISSUE TITLE
Uniques V2 Roadmap 2022 (Tracking Issue)

### ISSUE THREAD

**Issue by jsidorenko** [paritytech/substrate#11783]
## Goals

The main goal is to apply the best standards we currently have in the NFTs space while keeping the pallet as generic as possible.

### Changes to the existing core (Uniques V1):

- [x]  auto-incremental collections ids (https://github.com/paritytech/substrate/pull/12223)
- [x] new approvals structure ([Discussion thread](https://github.com/paritytech/substrate/discussions/11791)) (https://github.com/paritytech/substrate/pull/12178)
- [x] feature flags (bitflags) https://github.com/paritytech/substrate/pull/12367
- [ ] 	nested ownership ([Discussion thread](https://github.com/paritytech/substrate/discussions/11800))
- [x] support tips when buying an NFT (https://github.com/paritytech/substrate/pull/12168)

### New features:

- [x]  new minting methods ([Discussion thread](https://github.com/paritytech/substrate/discussions/11784)) https://github.com/paritytech/substrate/pull/12483
- [x] Atomic NFTs swap https://github.com/paritytech/substrate/pull/12285
- [x]  smart attributes (as described [here](https://forum.polkadot.network/t/uniques-pallet-nfts-september-update/410)) https://github.com/paritytech/substrate/pull/12702
- [ ]  multi-assets support
- [ ]  ~~new methods to sell NFTs with off-chain signatures~~ ([Discussion thread](https://github.com/paritytech/substrate/discussions/11792))
- [ ]  ~~basic support for marketplace functionality~~ ([Discussion thread](https://github.com/paritytech/substrate/discussions/11794)) (https://github.com/paritytech/substrate/pull/12189)

### Nice to have:

- [x]  refactor roles (extract into a separate data store) https://github.com/paritytech/substrate/pull/12437
- [x]  extract logic into features/[feature].rs files https://github.com/paritytech/substrate/pull/12570
- [ ]  advanced claiming options (Merkle tree claims, claims with the off-chain signature) 
- [ ] support 1155 token standard https://github.com/paritytech/substrate/pull/12565

**Comment by Szegoo** [comment]
What would the new approvals structure exactly be? Could you please provide a bit more details on that? Is there a document where these tasks are a bit more detailed?

**Comment by JayPavlina** [comment]
What is `multi-assets support`?

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/uniques-pallet-nfts-september-update/410/4

**Comment by shawntabrizi** [comment]
@JayPavlina tips is an opt-in approach to royalties, rather than building royalties, and knowing that users can bypass it easily using things like wrapping the token.

In this case, there is still a way for an original NFT creator to get paid some portion of a sale, which is via the TIP feature. You can imagine, if you buy any NFT on a platform which supports tips, they will make sure that the final purchase transaction handles the TIP amount, and the artist is paid. Obviously this is something that needs to be supported by the platform, but this is already true for enforcement of royalties

**Comment by jsidorenko** [comment]
@JayPavlina `Multi-assets support` is the ability to specify the price for your NFT in a non-native token.
No dex or conversion between tokens will be supported. If you set the price in USDC, then it will be possible to buy that NFT with USDC only.

Re smart attributes, I'll add them to the roadmap. Thanks for the heads up!

**Comment by takahser** [comment]
Can you include support for [SFTs](https://blockworks.co/web3-watch-what-are-semi-fungible-tokens-and-why-is-coinbase-making-a-movie/) (semi-fungible tokens, which are supported in [EIP-1155](https://eips.ethereum.org/EIPS/eip-1155)) in the roadmap as well? Major NFT marketplaces [have been supporting it](https://opensea.io/blog/announcements/erc1155-marketplace/) for a while already.

**Comment by jsidorenko** [comment]
I'll put it into Nice-to-have section for now. I think we should merge the new pallet into the master once we get the opened pull requests ready + the smart attributes implemented. After that, we could start to gather feedback and think about the next wave of improvements

**Comment by evilrobot-01** [comment]
The `mint` call/dispatchable currently requires an `item` to be specified, which could lead to transactions failing with `AlreadyExists` in a hyped public mint which sells out in seconds. Perhaps consider adding an option which allows items to be automatically assigned based on a requested quantity, to allow minting more than one item in a single transaction. This may also require mint limits per transaction and transaction limits per mint phase tho, depending on mint mechanics.

PS - There also currently does not seem to be a way to determine how many items have been minted (`CollectionDetails.items`) from another pallet, which could be used to determine the next item identifier to use with the current api.

**Comment by Lohann** [comment]
Hey, I think we are going to the wrong path here, I don't think Uniques pallet should support more features (auto-incremental collection id, nested ownership, etc)...

In my opinion, instead we should go to a path where we make Uniques minimal and easy to extend with new features, otherwise soon we will need to implement Uniques V3, because V2 doesn't support all features the community needs.

Example of things we want:
- [Bonding Curves](https://yos.io/2018/11/10/bonding-curves/) (I way for paying for minting tokens based in a curve)
- Handlers, like the [DustRemoval in pallet-balances](https://github.com/paritytech/substrate/blob/master/frame/balances/src/lib.rs#L218-L219) or transfer [OpenZeppelin's ERC20](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.7.3/contracts/token/ERC20/ERC20.sol#L344-L382), which makes possible to us to extend and react to events that happens in the uniques pallet.

Try to predict all use cases often imply flawed design, I would prefer a very simple and generic pallet that allow us to extend the mint/burn/freeze operations, pretty much like how [Ethereum's ERC-721](https://eips.ethereum.org/EIPS/eip-721) provides an interface and allow us to customize the behavior.

**Comment by Lohann** [comment]
In my ideal world, instead of [Features Flags](https://github.com/paritytech/substrate/pull/12367), I think the uniques pallets should be extensible pretty much like how [Substrate's SignedExtra](https://github.com/paritytech/substrate/blob/polkadot-v0.9.30/bin/node-template/runtime/src/lib.rs#L306-L315) allow us to extend Transactions, this way the community can focus on build extensions, instead create their own Unique's Pallet.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/statemint-update-roadmap/1200/1

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-37/1736/1
