### ISSUE TITLE
The rest of the way to Weights V2 (Tracking Issue)

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#12176]
Here is a tracking issue for all the steps I can think of, before we need to start going through all the various runtime logic, and actually use the new multi-dimensional weights v2.

- [ ] deprecate `RefTimeWeight` https://github.com/paritytech/substrate/pull/12157
- [ ] Remove `Ord` from the one dimensional weight type
    -  implement `any_gt` `any_lt` `all_gt` `all_lt` (and the equal to variant)
    - go through each comparison operator usage, and CAREFULLY make sure that it uses the correct version of `any_*` or `all_*`. This is super important, because it could lead to bugs if incorrectly implemented, and we have 2 dimensional weights.
- [ ] Then, I think we can finally add the second field to Weight without any worry, and just some storage migrations
    - [ ] We should also make the fields of Weight `#[compact]`, and include that in the migration: https://github.com/paritytech/substrate/issues/12149
    - [ ] We will also need to make frame executive respect both weight fields, and behave correctly.
    
Once we get to that point, we will need to double check our logic around benchmarking and PoV, and we can open a new tracking issue for that.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis/1026/2

**Comment by kianenigma** [comment]
I would also consider #13501 as critical part of considering this done.
