### ISSUE TITLE
Make depending on substrate easier

### ISSUE THREAD

**Issue by athei** [paritytech/substrate#12210]
# The Vision

Today, depending on substrate is not the best experience:

- You have to depend on a lot of small crates in your manifest and update them to upgrade to a new version
- The crates are not released to crates.io which prevents anyone using substrate from releasing there, too. This is especially annoying for tooling
- There is no semver: The API surface is huge and every release is breaking with regard to this API surface.

# The Plan

This is a huge undertaking where at the end there are separate repositories communicating over a well defined API via crates.io releases.  We will follow this incremental process:

- [ ] https://github.com/paritytech/substrate/issues/12209
- [ ] Create umbrella crates for substrate, and polkadot that expose a manually curated API surface that enables us to argue about semver
- [ ] Inter repo dependencies need to go through this wrapper crates on crates.io (no more companions)
- [ ] Move out parts (FRAME?) because now it is much easier to operate outside of the monorepo by depending on the umbrella crate

# Open Questions
_If you want to help us out and contribute to this issue, in this section you can find open questions and tasks where we would appreciate any input._
