### ISSUE TITLE
Compile the wasm runtime with a stable toolchain

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#1252]
We require nightly compiler for building the wasm runtime. The main reason for that is several important features was available only on the nightly compilers.

However, as the time progresses more and more features are promoted to stable.

- [x] alloc crate ([tracking issue](https://github.com/rust-lang/rust/issues/27783), [RFC](https://github.com/rust-lang/rfcs/pull/2480), [PR](https://github.com/rust-lang/rust/pull/59675))
- [x] `std::arch::wasm32::unreachable` ([tracking issue](https://github.com/rust-lang/rust/issues/61119))
- [x] `core_intrinsics` ([trie/hash-db](https://github.com/paritytech/trie/blob/283bf5ccf2d251bf2aa9cb51b42d3e728cc88a8f/hash-db/src/lib.rs#L17), not sure why)
- [x] waiting on `alloc_error_handler` becoming panic by default ([tracking issue](https://github.com/rust-lang/rust/issues/66741), [formelly this](https://github.com/rust-lang/rust/issues/51540))

**Comment by pepyakin** [comment]
The alloc crate is on the course of stabilization: [PR](https://github.com/rust-lang/rust/pull/59675)

**Comment by thiolliere** [comment]
alloc crate is stabilized by the way

**Comment by tomaka** [comment]
The biggest offenders for this are actually not in Substrate, but dependencies such as `elastic-array` or `hash-db`.
There seems to be way more than just `std::arch::wasm32::unreachable` missing.

**Comment by pepyakin** [comment]
- One dependency that still uses features is `safe_mix`. It does so needlessly and actually is already fixed on master (not published yet though).
- `core::arch::wasm32::unreachable` was landed and it allowed us to get rid of `core_intrinsics`, see #4823.
- `alloc_handler_error` is a real problem. We cannot work it around since `liballoc` requires its presence if used. There are some activity in discussion with some unhappy splats coming out of it, so 🤷‍♂

**Comment by athei** [comment]
What about dropping `#[no_std]`?  `wasm32-unknown-unknown` has a std target. It sounds weird that an `unknown`  has  std support but memory allocation is standardized in wasm so it can support it even without an explicit operating system. Any file system operation won't work of course (i.e panic). But that will make the runtime compile with stable.

Given that using nightly creates a a lot of friction and support overhead that might worth a shot.

**Comment by xlc** [comment]
@athei https://github.com/paritytech/substrate/issues/4043#issuecomment-552213702

**Comment by athei** [comment]
Thanks. Question is if those points are still valid a year later. I am just wondering how using a nightly only feature (whose definition is to be unstable) is considered more stable than using a stable compiler.

I see that this nasty std = native assumption would making the switch very painful, though.

**Comment by pepyakin** [comment]
I raised this question recently on a retreat, although with different reasons. The main concern in our discussion was the resulting binary size, and then the discussion spiraled into other realms. I was of opinion that there should be a minor increase in binary size which should be fine. I never checked though.

An argument against I heard back is that we are still changing nightlies every now and then because something breaks, or something. But I am not sure if I buy this argument. I am pretty sure that all our stuff works on many previous stable compiler versions.

As to Wei's list, 

- I don't think that no_std=wasm assumption is very painful. I think we might get away by introduction of another feature. In fact, there is a PR #7275 (issue https://github.com/paritytech/substrate/pull/5547). Long term, this is related to #7288 
- I don't buy the determinism argument. I would argue that no_std/std doesn't change anything with that regard. In this context, I heard sometimes that allegedly `HashMap` would be non-deterministic, but it doesn't change that the wasm binary has to obtain entropy from somewhere and the host doesn't provide it anyway.
- The stability is indeed tricky. In libstd/sys one can find this [stability warning](https://github.com/rust-lang/rust/blob/6e9a1de0d146734e51cc7e761b288e9b9b138d4f/src/libstd/sys/wasm/mod.rs#L1-L1). IMO this doesn't matter though. It's not like we would switch to allow use the std stuff: of course no. mutexes, entropy, filesystems, networking will still be unusable, and we don't care if that changes. Then I don't see how these things can change because the wasm32-unknown-unknown cannot import anything from the environment. The other stuff I either see not changing (panics) or we override that anyway (allocations). As a data point, this part stays the same for three years already.

The biggest problem from the list is that the libstd is available and will panic on unsupported operations. Although I think it's unlikely, but still not impossible, e.g. that some crate dependency tries to spawn a thread. I don't see a plausible way to check that without going to inspect MIR or something alike.

On the other hand, I think one would need to put a lot of effort in order to accidentally get such an issue even on a testnet: that implies no inspection and no testing.

That said, I think it is very unlikely that we get `alloc_error_handler` stabilized soon and compiling runtime on stable does sound interesting.

**Comment by athei** [comment]
> I don't think that no_std=wasm assumption is very painful. I think we might get away by introduction of another feature. In fact, there is a PR #7275 (issue #5547). Long term, this is related to #7288 

I agree. Using a proper feature was always the right thing to do that. It is just that this fact will add a lot of code churn to the transition. But still more of a mechanical change than something difficult.

> I don't buy the determinism argument. I would argue that no_std/std doesn't change anything with that regard. In this context, I heard sometimes that allegedly HashMap would be non-deterministic, but it doesn't change that the wasm binary has to obtain entropy from somewhere and the host doesn't provide it anyway.

We could still avoid `HashMap`. Not everything that would be able to be used is to be used. Maybe we can create (or there is even something like it already) that works like `cargo-deny` just for imports to make sure only whitelisted stuff from `std` can be imported.

**Comment by pepyakin** [comment]
(My point is that I don't see a big reason to avoid `HashMap`)

**Comment by athei** [comment]
I get that. However, buying into your point is not necessary for using std. We can still continue to not use it.

**Comment by pepyakin** [comment]
> With LTO enabled unused functionality should be removed effectively. I also don't expect a huge impact. It mainly gets huge when using the included memory allocator which we will not.

Yeah, that takes into account effects of LTO. The problem is that the libstd builds use some additional machinery (IIRC, it was around panics).

Also, perhaps related. There were discussions about introducing a custom target. https://github.com/paritytech/substrate/issues/4225

**Comment by shawntabrizi** [comment]
@pepyakin should this be closed or moved?

**Comment by pepyakin** [comment]
Nope, still relevant.

**Comment by NukeManDan** [comment]
https://github.com/rust-lang/rust/issues/51540#issuecomment-877939875
> The consensus was to not stabilize #[alloc_error_handler] for now and instead make it panic by default as proposed in https://github.com/rust-lang/rust/issues/66741. However I don't believe there has been any progress towards implementing this so far.

Just checking in here as a curious substrate user :) I see the last item in the OP is likely going a different direction. Will this be a blocker?

**Comment by pepyakin** [comment]
No, not really.

Right now, we have to specify `alloc_error_handler`. In case it's absent, the compilation will fail. If I understand correctly, they want it to make OOM panic by default, and I assume that implies that you will be able just to omit the `alloc_error_handler`. Thus we will be able to omit it and rely on panics in OOM.

We use `alloc_error_handler` as an opportunity to provide some diagnostics. We will have to sacrifice that. I don't think this is a big deal though. I'd pick compiling with stable instead.

**Comment by MrishoLukamba** [comment]
So Should we use stable toolchain for compilation or still nightly?

**Comment by athei** [comment]
It is still nightly. There is no stable way to use `alloc` in a `no_std` binary.

**Comment by NukeManDan** [comment]
1.67 this should be included then? What actions are needed on ops and tooling to move to stable once once it is?

- docs updated, 
- ci/cd images and scripts remove nightly ( if possible, might need it for fmt still? Perhaps a reason to update rustfmt to be stable only)
- tooling removes nightly (zombienet et.al.)
- ...what else?

**Comment by athei** [comment]
wasmbuilder needs to be changed to use a stable toolchain instead of defaulting to the latest installed nightly compiler.

We still use nightly for rustfmt. This is also executed inside the CI. So purging nightly from all our CI images is not possibly unless we are willing to move to stable rustfmt (and losing some formatting rules).

**Comment by gilescope** [comment]
Loosing the odd formatting rule seems a small price to pay tbh. I don't think that should hold us back.

**Comment by athei** [comment]
Rust 1.67 landed. We can compile the runtime with stable now if we use the default `alloc_error_handler`. However,  since the opening of this issue stuff was put into this error handler to report the oom error to the client.

@koute Can we remove this error from the alloc error handler for the sake of compiling with stable? Maybe we can put the logging into the client side allocator? It can write a log when it can't fulfil a memory request which should lead to an panic.

**Comment by bkchr** [comment]
> @koute Can we remove this error from the alloc error handler for the sake of compiling with stable? Maybe we can put the logging into the client side allocator? It can write a log when it can't fulfil a memory request which should lead to an panic.

We can remove it. The feature isn't currently active and oom should be detected by our allocator anyway on the host side. Not sure if this is even triggered somehow.

**Comment by athei** [comment]
Apparently it is not in 1.67. I thought since [it was merged](https://github.com/rust-lang/rust/pull/102318) mid December.

**Comment by koute** [comment]
> @koute Can we remove this error from the alloc error handler for the sake of compiling with stable? Maybe we can put the logging into the client side allocator? It can write a log when it can't fulfil a memory request which should lead to an panic.

Yeah that's fine.

As Basti said, I'm not entirely sure if it's actually possible to trigger it. That callback is called by the `alloc` crate when memory allocation fails, but our allocator never returns NULL and just panics inside of the host function if there's an allocation failure.

**Comment by athei** [comment]
Great. Thanks for the explanation. In that case the handler should never called indeed. Then I do this a as soon as a stable version with this is released.

**Comment by chevdor** [comment]
I prepared a new `srtool` image based on Rust 1.67.0 and not using the dirty trick mentioned above.

A build can be tested from [this workflow](https://github.com/paritytech/srtool/actions/workflows/manual.yml) with a manual start (workflow dispatch) and some input similar to what is shown below:

<img width="361" alt="image" src="https://user-images.githubusercontent.com/738724/215510521-7dcc5b61-efb2-4307-8d32-fca5177b99d9.png">

The most import being to use the proper Docker image: `chevdor/srtool:1.67.0-0.10.0-d498197-alpha`

**Comment by athei** [comment]
Didn't we just discover that it doesn't work with 1.67?

**Comment by chevdor** [comment]
I missed that part @athei. I can update and make a new image with 1.68 or whenever it lands so we can test and confirm.

**Comment by Dengjianping** [comment]
Now, rust 1.68 has been released.

**Comment by athei** [comment]
Nice. I will make a PR. @chevdor can you prepare an image with the new stable version?

**Comment by chevdor** [comment]
@athei yep I started already and found an issue in srtool, which is now fixed and merged.
So I will rebuild an image and we can test when those PRs above are merged.

**Comment by athei** [comment]
> I have created another version (hadn't seen your pr, but also started earlier) that is fully backwards compatible: #13580

Closed mine. I think your non breaking version makes more sense for the transition.
