### ISSUE TITLE
Tracking issue for adding `try_state` hook to all pallets. 

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#12831]
This is the tracking issue to add the `try_state` hook to as many pallets as we can. 

This hook was added in https://github.com/paritytech/substrate/pull/10174. The idea is as follows: 

```rust
/// Execute some checks to ensure the internal state of a pallet is consistent.
///
/// Usually, these checks should check all of the invariants that are expected to be held on all of
/// the storage items of your pallet.
///
/// This hook should not alter any storage.
pub trait TryState<BlockNumber> {
	/// Execute the state checks.
	fn try_state(_: BlockNumber) -> Result<(), &'static str>;
}
```

So, the ideas is to focus on invariants that must always be held in a pallet. A native, yet important example of this is that in the balances pallet, iterating over all users should yield the correct total issuance. 

Next, we want all pallets to call their `try_state` after each test. This can easily be achieved with a helper function like: 

https://github.com/paritytech/substrate/blob/dd8a34775aab9b362a5cc7552d5603c2fe812f82/frame/nomination-pools/src/mock.rs#L335

```
pub fn build_and_execute(self, test: impl FnOnce() -> ()) {
	self.build().execute_with(|| {
		test();
		// run the try-state of all pallets after each test.  
		<Runtime as TryState>::try_state(_, TryStateSelect::All).unwrap();
	})
}
```

- [ ] alliance
- [ ] assets
- [ ] atomic-swap
- [ ] aura
- [ ] authority-discovery
- [ ] authorship
- [ ] babe
- [x] bags-list
- [ ] balances
- [ ] beefy
- [ ] beefy-mmr
- [ ] bounties
- [ ] child-bounties
- [ ] collective
- [ ] contracts
- [ ] conviction-voting
- [ ] democracy
- [ ] election-provider-multi-phase
- [ ] election-provider-support
- [ ] elections-phragmen
- [ ] examples
- [ ] fast-unstake
- [ ] gilt
- [ ] grandpa
- [ ] identity
- [ ] im-online
- [ ] indices
- [ ] lottery
- [ ] membership
- [ ] merkle-mountain-range
- [ ] multisig
- [ ] nicks
- [ ] node-authorization
- [x] nomination-pools
- [ ] offences
- [ ] preimage
- [ ] proxy
- [ ] randomness-collective-flip
- [ ] ranked-collective
- [ ] recovery
- [ ] referenda
- [ ] remark
- [ ] root-offences
- [ ] root-testing
- [ ] scheduler
- [ ] scored-pool
- [ ] session
- [ ] society
- [x] staking
- [ ] state-trie-migration
- [ ] sudo
- [ ] support
- [ ] system
- [ ] timestamp
- [ ] tips
- [ ] transaction-payment
- [ ] transaction-storage
- [ ] treasury
- [ ] try-runtime
- [ ] uniques
- [ ] utility
- [ ] vesting
- [ ] whitelist

Implementing this hook will allow these checks to be called in `try-runtime-cli`, and other testing tools that compile a runtime with `feature = try-runtime`. 

Note that for those who want to tackle a particular pallet, you must for sure deeply understand a pallet in order to correctly identify its list of invariants. Moreover, you might do your future generation a favor by documenting the invariants as good as you can.

**Comment by vjgaur** [comment]
Can I take this up ?

**Comment by kianenigma** [comment]
> I want to take this up. Can you please assign this to me ?

This is a tracking issue, you can go ahead and work on any item, no need to assign 👍

**Comment by ggwpez** [comment]
> The idea of the `try_state` hook is to reduce testing code?

There are actually two advantages that `try_state` has. Once for invariant assertion in unit tests, but also in try-runtime migration testing.  
So the goal is to increase test coverage by always checking the invariants. So it would probably end up with *more* testing code, not less :laughing:   
There is some more explanation here https://github.com/paritytech/substrate/issues/13115#issuecomment-1380218189

**Comment by MrishoLukamba** [comment]
> [ ]

**Comment by Doordashcon** [comment]
@ggwpez could I list out pallets I think won't require `try_state` ? For now _pallet-timestamp_ which uses the `#[pallet::inherent]` and _pallet-utility_ which is stateless.

Hoping this might speed things up for other contributors :)

**Comment by ggwpez** [comment]
Yes sure @Doordashcon. Marked them together with the nicks pallet.

**Comment by Szegoo** [comment]
I will start working on the try-state for the referenda pallet if no one else picked that already.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/discussion-shaping-the-future-of-try-runtime-and-try-runtime-cli/2657/4

**Comment by pmikolajczyk41** [comment]
aura implemented here: https://github.com/paritytech/substrate/pull/14363
