### ISSUE TITLE
[Meta] Reactivate `frame-coders` team

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#13791]
Reactivate the @paritytech/frame-coders team.  

Tasks:
- [ ] Update the member list
- [ ] Add folders to the CODEOWNERS file
- [ ] Add review rules regarding the owned files

**Comment by bkchr** [comment]
A team can host in maximum `10` members, after that each member costs `$3.09` per month :smiling_face_with_tear: 

People can just add themselves to the relevant files they want to be CODEOWNERS of, not sure the team is needed.

**Comment by ggwpez** [comment]
> A team can host in maximum `10` members, after that each member costs `$3.09` per month smiling_face_with_tear

:exploding_head: 

Maybe we can use the custom GHA instead together with codeowners to get something like the team approvals.

**Comment by bkchr** [comment]
> with codeowners to get something like the team approvals.

I'm against requiring a fixed set of people to approve certain changes. I mean we already see the bottleneck in Polkadot with the locks review. Or you just want to ping them?

**Comment by ggwpez** [comment]
> I'm against requiring a fixed set of people to approve certain changes. I mean we already see the bottleneck in Polkadot with the locks review. Or you just want to ping them?

Hm okay. I was under the impression that the sdk-node team approvals work quite well in Substrate. The FRAME team now consists of ~13 people, so there is not such a big bottleneck i think.  
WDYT @kianenigma ?

**Comment by bkchr** [comment]
> I was under the impression that the sdk-node team approvals work quite well in Substrate.

There are no required approvals/CODEOWNERS from the team. 

We can also create the team and add the people. I think parity should be able to pay these 3$ :D

**Comment by kianenigma** [comment]
> > I'm against requiring a fixed set of people to approve certain changes. I mean we already see the bottleneck in Polkadot with the locks review. Or you just want to ping them?
> 
> Hm okay. I was under the impression that the sdk-node team approvals work quite well in Substrate. The FRAME team now consists of ~13 people, so there is not such a big bottleneck i think. WDYT @kianenigma ?

If you look at the FRAME PRs, I think often the reviews come from the the actual 13 mentioned developers, but I think especially given the overlap with the common goods parachain, we might stall their work if we mandate @paritytech/frame-coders to approve their PRs. 

If so, we can make one approval from @paritytech/frame-coders mandatory, but I would certainly say not two, at least not right now. Perhaps in 6-12 months, in the new mono-repo, we can revisit such a rule.

**Comment by bkchr** [comment]
https://github.com/paritytech/pr-custom-review should be able to set these granular rules.

**Comment by juangirini** [comment]
> https://github.com/paritytech/pr-custom-review should be able to set these granular rules.

Oh that's great, thanks for pointing it out

**Comment by ggwpez** [comment]
@juangirini I think @s3krit is in the team only for historical reasons.  
Could you please remove him from there?

**Comment by juangirini** [comment]
> @juangirini I think @s3krit is in the team only for historical reasons. Could you please remove him from there? (also means less notifications for him 😆 )

happy for him 😄 just removed
