### ISSUE TITLE
Statement store

### ISSUE THREAD

**Issue by arkpar** [paritytech/substrate#13893]
This is a tracking issue for implementing https://github.com/paritytech/labs/issues/3

- [x] Basic store implementation #13701
- [ ] Encryption support (depends on #13832)
- [ ] Statement prioritization in the network protocol.
