### ISSUE TITLE
[Meta/PM] Update CODEOWNERS

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#14054]
```[tasklist]
## Todo
- [x] Update rules for `sp-artithmetic` and more
- [x] Old users should be replaced
- [x] Make frame-coders own `/frame/`
```
