### ISSUE TITLE
tracking issue for full unleash of `DefaultConfig` for FRAME

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#14234]
https://github.com/paritytech/substrate/pull/13454 will bring in the basic functionality needed to start using this feature. See this example to learn more. 

This will mark the first version of this work complete, but a lot has to be done in order for it to be fully complete.

## Improve Error Handling, Bugs

* [ ] Improve error handling. There seems to be an error in the `parse/config.rs` file that allows `#[pallet::whatever]` to be parsed and ignored in `#[pallet::config]`. This has to be fixed.

## Full usage in Substrate Pallets 

* [ ] migrate the docs for `derive_impl` to use real code. As all of this functionality can work on normal traits, and as per #14115, we should strive to make the docs of `derive_impl` be real rust code. 
* Provide testing defaults for common pallets
  * [x] System: already provided
  * [ ] Balances
  * [ ] Timestamp
  * [ ] ...?
* Then, we should start migrating existing pallets and their test setup to use the unified testing prelude of system, balances and so on. Here's a tracking list: 
  - [ ] alliance
  - [ ] asset-conversion
  - [ ] asset-rate
  - [ ] assets
  - [ ] atomic-swap
  - [ ] aura
  - [ ] authority-discovery
  - [ ] authorship
  - [ ] babe
  - [ ] bags-list
  - [ ] balances
  - [ ] beefy
  - [ ] beefy-mmr
  - [ ] bounties
  - [ ] child-bounties
  - [ ] collective
  - [ ] contracts
  - [ ] conviction-voting
  - [ ] core-fellowship
  - [ ] democracy
  - [ ] election-provider-multi-phase
  - [ ] elections-phragmen
  - [ ] executive
  - [ ] fast-unstake
  - [ ] glutton
  - [ ] grandpa
  - [ ] identity
  - [ ] im-online
  - [ ] indices
  - [ ] insecure-randomness-collective-flip
  - [ ] lottery
  - [ ] membership
  - [ ] merkle-mountain-range
  - [ ] message-queue
  - [ ] multisig
  - [ ] nft-fractionalization
  - [ ] nfts
  - [ ] nicks
  - [ ] nis
  - [ ] node-authorization
  - [ ] nomination-pools
  - [ ] offences
  - [ ] preimage
  - [ ] proxy
  - [ ] ranked-collective
  - [ ] README.md
  - [ ] recovery
  - [ ] referenda
  - [ ] remark
  - [ ] root-offences
  - [ ] root-testing
  - [ ] salary
  - [ ] scheduler
  - [ ] scored-pool
  - [ ] session
  - [ ] society
  - [ ] staking
  - [ ] staking-bags-benchmarks
  - [ ] state-trie-migration
  - [ ] statement
  - [ ] sudo
  - [ ] system
  - [ ] timestamp
  - [ ] tips
  - [ ] transaction-payment
  - [ ] transaction-storage
  - [ ] treasury
  - [ ] try-runtime
  - [ ] uniques
  - [ ] utility
  - [ ] vesting
  - [ ] whitelist

## Full Usage in `node-template-runtime` and `parachain-template-runtime`

We should provide runtime templates that utilize this, evangelising its usage. This requires us to carefully consider what is a reasonable default for a node template in order to use. We should provide possibly two new preludes: 

## Full usage in `westend` -> `kusama` -> `polkadot` runtimes. 

Once we have are more and more confident in both the core functionality, and our skills to define sensible defaults, we can slowly start migrating perhaps some of the configs define in Polkadot to use this feature. 

For security reasons we should be super caution here. Adding `#[derive_impl]` will open the door for upstream changes manipulating the configurations used in the Polkadot runtime. Perhaps we should only ever do this once we have more tooling that could notify us of unexpected upstream changes to `config_preludes`. 

I would personally find it reasonable to never use this feature in production runtimes for this reason. 

## V2

At the moment, the system that is introduced is has some limitations. Most notably: 

- [ ] it cannot provide default for types that are reliant on types that are themselves reliant on `frame_system::Config`. For example, a `type Admin: Get<Self::AccountId>` cannot have a default. Is is mainly because `trait DefaultConfig` is not in itself `trait DefaultConfig: frame_system::DefaultConfig`. Moreover, sadly, because the definition of `BalanceOf<T>` (somewhat needlessly) also relies on `frame_system::Config::AccountId`, anything akin to `Get<BalanceOf<Self>>` can also not have a sensible default. 

I believe this is father easy to fix, by standardizing `frame_system::DefaultConfig` and making `trait DefaultConfig: frame_system::DefaultConfig`. 

- [ ] If the above is done, we are only left with types that cannot really have a default in any pallet. Such types are: `PalletInfo`, `RuntimeEvent`, `RuntimeCall` and such. Such types can also be mocked but they require more coordination with `construct_runtime!`. A new attribute can mark these types simply as `#[derive_from_runtime]` or similar, which would mean they are expected to be found in the existing scope with the same name. 

Other approaches could be explored for the last step, as I am not quite sure what is the best way forward.

**Comment by bkchr** [comment]
> * it cannot provide default for types that are reliant on types that are themselves reliant on `frame_system::Config`. For example, a `type Admin: Get<Self::AccountId>` cannot have a default. Is is mainly because `trait DefaultConfig` is not in itself `trait DefaultConfig: frame_system::DefaultConfig`. Moreover, sadly, because the definition of `BalanceOf<T>` (somewhat needlessly) also relies on `frame_system::Config::AccountId`, anything akin to `Get<BalanceOf<Self>>` can also not have a sensible default.

Personally I would say that we do this before we do all the other things, otherwise you will start changing all this code twice. I already left a comment here on how it could work: https://github.com/paritytech/substrate/pull/13454#issuecomment-1495855632

In general to this feature, I had some idea recently which could improve the versioning around our crates. Currently when we are adding a new type to a `Config` trait it requires that we bump the major version of the crate. If we have the system outlined here working and it is being used everywhere. (I would even go that far and say it is fine to use it in production runtimes, at least having the attribute above each `Config` implementation) Then we could introduce some kind of "versioning" of these `Config` traits. Then every time you would add a new config type, you would bump this version in your pallet. We would then only require to bump the `minor` version. Downstream users would then at some point bump the pallet minor version. It would still compile, because the attribute above the `impl Config` would put there some safe/secure default value. But it would also generate a warning that tells the user that it put there some new type. It could even show some more context to the new type added. The user can accept the new safe default value by bumping the "trait version to use" or they just add the type on their own and bump the trait version in use. 
Not sure if this idea is something we should really do, but I wanted to leave it here :P

**Comment by sam0x17** [comment]
is the parse issue still present with `#[pallet::whatever]`?

**Comment by sam0x17** [comment]
potential vast improvement: https://github.com/paritytech/substrate/pull/14437#discussion_r1251861668
