### ISSUE TITLE
Off-chain oracle modules

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#1458]
Currently it's impossible for code on-chain to access data off-chain except via hard-coded `InherentData`. This would make it entirely programmable.

There are two components:
- A runtime module that keeps track of the blobs of wasm code that block authors are expected to run prior to block formation which populate the `InherentData` that will thereafter be fed into the runtime.
- The according piece of client logic that checks for the existence of this runtime module, and if extent, grabs the wasm blob, constructs an appropriate (non-deterministic) wasm environment and calls a given function (e.g. `fn get_inherent_data() -> HashMap<Vec<u8>, Vec<u8>>` - the function should be infallible since to fail would render the chain dead). The environment should include general internet access, secure random number generation, timing, secure enclave access and any other useful hardware externalities. (A later version should introduce a fine-grained permissioning system for these.) The result of the function should be amalgamated into the `InherentData` for the runtime to utilise.

An example module should be constructed that places the timestamp into an `InherentData` key.

**Comment by burrrata** [comment]
I'd like to better understand how this would work and contribute if I can. @tomusdrw @gavofyork what is the best place to ask questions and contribute code or ideas?

**Comment by tomusdrw** [comment]
Hi @burrrata, reach me out on riot: `@todr:matrix.parity.io` please

**Comment by tomusdrw** [comment]
To be done: implementation of methods exposed in #2615:

- [x] `submit_transaction` - submit a transaction to the pool
- [ ] `random_seed` - return a random seed (nondeterministic; local)
- [ ] `sign` - sign a piece of data with pre-configured key (most likely authorities key)
- [ ] `local_storage_read/write` - save and read stuff between offchain workers runs
- [ ] HTTP apis - fetch stuff from the web

**Comment by supercoder123456** [comment]
@tomusdrw, Is there any example about off-chain worker? Do you have riot id also?

**Comment by tomusdrw** [comment]
@supercoder123456, not much examples yet, I want to make the offchain workers a bit more functional before writing some. 
The only docs can be found here:
https://github.com/paritytech/substrate/blob/7d7981c7fd472cb94d1dc5c727d15464b1bf1f74/srml/example/src/lib.rs#L472

I'm available on riot as well @todr:matrix.parity.io

**Comment by lingqingmeng** [comment]
I can create an off-chain oracle (non-deterministic) for Substrate using BLS281, who can I talk to for more information on the specific requirements on this?

**Comment by gavofyork** [comment]
All good.
