### ISSUE TITLE
[Deprecation] Remove `Balance::set_balance_deprecated`

### ISSUE THREAD

**Issue by juangirini** [paritytech/substrate#14653]
`force_set_balance` should be used instead
```[tasklist]
### Tasks
- [ ] Hard deprecation by adding a warning message *
- [ ] Remove usage of the deprecated feature in the code base
- [ ] Update examples and tutorials
- [ ] Deprecation is noted in the release log
- [ ] Removal version is planned
- [ ] Deprecated feature is removed
- [ ] Removal of the feature is noted in the release log
```
