### ISSUE TITLE
[Deprecation] Treasury Proposal Dispatchables 

### ISSUE THREAD

**Issue by muharem** [paritytech/substrate#14732]
The old treasury pallet's dispatchables to create/reject/approve a proposal now replaced by the `spend` dispatchable.

Deprecated dispatchables:
- pallet_treasury.propose_spend
- pallet_treasury.reject_proposal
- pallet_treasury.approve_proposal

The `pallet_treasury.remove_approval` dispatchable is not deprecated since its still can be used to remove an approved proposal by the `spend`.

```[tasklist]
### Tasks
- [ ] Hard deprecation by adding a warning message *
- [ ] Remove usage of the deprecated feature in the code base
- [ ] Update examples and tutorials
- [ ] Deprecation is noted in the release log
- [ ] Removal version is planned
- [ ] Deprecated feature is removed
- [ ] Removal of the feature is noted in the release log
```

**Comment by muharem** [comment]
@oshakarishvili can you help me with finding the existing examples and tutorials concerning the deprecated dispatchables?

**Comment by oshakarishvili** [comment]
Following our transition from **Gov1** to **OpenGov**, comprehensive updates have already been made to all our documentation and guidelines (you can find one of several examples on our [wiki](https://wiki.polkadot.network/docs/learn-polkadot-opengov-treasury#creating-a-treasury-proposal) or [Scribehow](https://scribehow.com/shared/How_to_Submit_a_Polkadot_OpenGov_referendum_for_a_treasury_proposal__lvcYGpIqQ6GPSn9gvMO-KQ) for detailed step-by-step). Due to these updates, the usage of the `propose_spend` call has become quite rare, given the evolved context. The remaining two calls (`reject_proposal` and `approve_proposal)` primarily found use within the council, hence detailed documentation for these calls has been limited historically.
