### ISSUE TITLE
Networking roadmap

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#1692]
Here are some steps that I have in mind for the `network` crate, ordered in order to have a smooth transition. Feel welcome to comment.

- [x] Make `Service` and `ServiceEvent` generic over the message type, and send/receive messages instead of `Bytes` objects.
- [x] Add a trait in `network-libp2p` that is implemented on `Message` and allows retrieving the `RequestId`.
- [x] Make `network-libp2p/src/custom_proto/handler.rs` open a new substream for each request. Whether to wait for an answer and how to associate substreams with requests is done using the trait mentioned in the previous point. (#1517)
- [ ] Remove the `Clogged` event.
- [ ] (blurry) Rewrite `network/src/protocol.rs` as a libp2p `NetworkBehaviour`. Instead of passing a `RegisteredProtocol` to `network-libp2p`, one can pass a `NetworkBehaviour`. Move `network-libp2p/src/custom_protocol` to `network`. The messages generated by the API of network-libp2p's `Service` would be the events generated by the network behaviour. We would also require a trait in addition to `NetworkBehaviour` so that we can register discovered nodes to the behaviour.
- [ ] Move some logic from the `protocol.rs` NetworkBehaviour into the `ProtocolsHandler`, such as the `Status` message. After this point, #1518 and #1702 can be tackled.
- [x] ~~Extract the gossiping from `protocol.rs` to use a different protocol from the rest (the rest meaning things such as block or header requests).~~
- [x] ~~(blurry) Use libp2p's floodsub, episub or gossipsub instead of `consensus_gossip` (#366)~~.
- [ ] Change everything to use futures and messages passing instead of `Arc`s (#834), and use `tokio-timer` instead of `maintain_peers`, `tick` or `garbage_collect`.
- [ ] Merge `network` and `network-libp2p`?

Later:
- [ ] Remove backwards compatibility for #1517.
- [ ] Remove the `RequestId` from `network::message::Message` and let libp2p do the ID assignment.

**Comment by tomaka** [comment]
The current step is more or less "Rewrite network/src/protocol.rs as a libp2p NetworkBehaviour" now.

For this step, I'm going to change a bit the API of `substrate-network-libp2p`.
At the moment, it is an opaque state machine where you open/close connections with remote, and read/write messages.

After this step, the `ServiceTask` struct would accept two template parameters: a discovery protocol, and a gossiping protocol. They would both be defined by traits in `substrate-network-libp2p`. The discovery protocol would generate events that are then indirectly reflected on the gossiping protocol, and the gossiping protocol would generate events that are propagated to the outside of the `ServiceTask`.

The text mentions "Move network-libp2p/src/custom_protocol to network.", but I wouldn't do that in the end. The `substrate-network-libp2p` crate would provide implementations of the discovery and gossiping traits that could be used by whatever code uses `substrate-network-libp2p`.

**Comment by gterzian** [comment]
@tomaka Do you need help with "Rewrite network/src/protocol.rs as a libp2p NetworkBehaviour"?

**Comment by tomaka** [comment]
The first step was https://github.com/libp2p/rust-libp2p/pull/1046 in libp2p. Once a libp2p version is published I'll finish my work in progress PR.

**Comment by tomaka** [comment]
I'm going to close this issue, as half of it is implemented and only #2374 is still important.
