### ISSUE TITLE
Usage of twox_128 / XxHash 

### ISSUE THREAD

**Issue by burdges** [paritytech/substrate#1868]
We've had a concern raised in section 4.6.1 of the Secfault audit about the usage of twox_128 / XxHash in https://github.com/paritytech/substrate/blob/master/srml/support/src/storage/mod.rs

Can anyone explain it's usage there?  As it's storage, we're probably only talking about a DoS risk, right?  Is there some preliminary hashing phase that then xxhash only gets used in the tree itself?  I suppose that's okay when some local secret gets used, but if this storage mirrors other nodes then maybe worse attacks exist?

**Comment by thiolliere** [comment]
I don't know about usage of the trie in core but here is a description of trie usage in SRML:

## Abstraction provided:

srml/support provides abstraction on trie:
* with a hash abstraction https://crates.parity.io/srml_support/storage/index.html
  does hash key with twox_128 before using it in the trie
* a unhashed abstraction https://crates.parity.io/srml_support/storage/unhashed/index.html
  which insert, get with the key directly
* an unhashed abstraction on children https://crates.parity.io/srml_support/storage/unhashed/index.html

But user (and our srml modules) usually doesn't use it.
instead it uses decl_storage macro that uses those abstraction to provides a way to define multiple storages over the trie.

those are defines https://crates.parity.io/srml_support_procedural/macro.decl_storage.html
decl_storage takes as input the name of the module and storage names and type and generate a structure for each storage. Here how it works for the different types:

* storage value: final key is `twox_128(concatenation of(modulename, storagename))`. those input are trusted, its fine.

* storage map: for each storage map key it insert into the trie the key: `twox_128(concatenation of(modulename, storagename, encode of key))`.
  the encode of key is usually implemented using parity-codec which just provides an optimised way to represent the key in bytes.
  /!\ depending on where does key comes from this might be problematic, this is not told by the doc and we might should review our usages.

* storage linked map: key is build same as storage map.

* storage double map: (associate two key to a value and provide an efficient way to remove all association from key1), we provide a way to specify the hasher used (among blake2_256, twox_128 and twox_256) 
  final insertion is
  `concatenation_of(twox_128(ModuleName, storagename, key1), hasher_specified(key2))`
  some same issue as storage map for first part.

Some structure are also provided out of decl_storage:

* StorageVec: trait requires a prefix and then key are `twox_128(concatenation_of(encode of index, PREFIX))`
* unhashed StorageVec: `concatenation_of(PREFIX, encode of index)` seems fine.
* StorageList: `twox_128(concatenation of(PREFIX, index))`
* StorageDoubleMapWithHasher: requires to provide the implementation of derive_key1 and derive_key2: final key is concatenation of both derivation

## Usages in SRML:

* StorageVec, StorageDoubleMapWithHahser, StorageList: not used

`grepe . -rne 'map .*=>' --exclude-dir support` maybe problematic keys are is:
* AccountId
* CodeHash
* AccountIndex in indices
* AssetId in asset
* some Hash in council

## TODO:

* [ ] storages provided by decl_storage never state the possible threats if any with twox_128 ?
* [ ] maybe documentation should be precised for all abstraction provided
* [ ] are keys of map ok ?

if we need to evolve from that:
* moving from xx_128 to blake2_256 is quite straightforward
  * except DoubleMap may not work because it could have its key being concatenation of blake2_256, blake2_256 thus exceed max trie key lenght ? @cheme 
    although we can just change the choice in doublemap to be blake2_128.
* making decl_storage provide a the choice for the hasher seems doable and not that difficult.
  * a possibility could be changing default to blake2_256 and making user able to specify hasher. Thus current code won't break but just be slower by default

notes: This would break the current storage ? I have no idea about this part, I only put into light our current usage. And I don't have that much idea about performance implication.

@kirushik

**Comment by cheme** [comment]
@thiolliere I did a mistake when doing this assumption (I was considering code from trie/reference-trie that only encode over one byte, but in fact code from substrate crate for the encoding is a bit different and will add an additional byte).
So using 256 + 256 will just add an additional byte in the encoding of a trie node.

**Comment by burdges** [comment]
I haven't looked into the code really, but if I understand there should be two hash function usages here:  First, anything inserted into the trie should use a key that's hashed, so any collisions would be a major problem here.  Second, any such hashes inserted into the tree must be pushed through the merkle tree hashing to compute the root.  I think the second sounds much less vulnerable than the first, but maybe not so immune as to allow a really weak hash function like xxHash.

**Comment by burdges** [comment]
I'm no expert in symmetric crypto so I've asked a crypto.SE question on this, which we can forward to others if no convincing answers appear.  https://crypto.stackexchange.com/questions/68704/round-counts-and-permutation-usage-for-hashing-for-a-merkle-tree

**Comment by kirushik** [comment]
@burdges I'd suggest we first benchmark Substrate with BLAKE2, and only look in the direction you're pointing if that will not be satisfactory. (I don't even think we're using all the performance-optimization features of our BLAKE library at the moment.)

**Comment by bkchr** [comment]
Can we close this?

**Comment by thiolliere** [comment]
yes all storage map have default to blake2_256, and using twox_128 is opt-in.
