### ISSUE TITLE
repo reorg tracking issues

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#4099]
First batch in #4074 .

Next up:
- [x] remove `palette`-dependencies from `client` (move inherents to primitives):
- [x] move into primitives: #4184
- [x] rename all the crates to their area:
  - [x] `/primitives`: prefixed `sp-`
  - [x] `/client`: prefixed `sc-`
  - [x] clean up aliases, enforce long name usage
- [x] update versions, to bump below 1.0:
  - [x] networking
  - [x] consensus
- [x] remove client internal deps:
  - [x] basic-authorship
  - [x] aura
  - [x] babe
  - [x] finality-grandpa
  - [x] client-db
  - [x] network
  - [x] rpc
- [x] test reorg:
  - [x] network

probably post 2.0:
- [ ] merge remaining client into service
- [ ] clean up frame-support
- [ ] clean up frame-system
- [ ] Merge sp-serializer with sp-core or sp-runtime

**Comment by gnunicorn** [comment]
PR pending. closing.
