### ISSUE TITLE
Tracking issue for enabling wasmtime

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#4189]
Before promoting the wasmtime wasm backend from hidden behind a cargo feature to just experimental (still off by default) we need to:

- [x] clean some questionable unsafe code, 
- [x] aliasing violations, see https://github.com/paritytech/substrate/issues/4599
- [ ] to make it compile (NOT run) on ARM, see #4188
- [ ] zeroing for imported memories https://github.com/paritytech/substrate/issues/5036

**Comment by pepyakin** [comment]
I think this can be closed now.
