### ISSUE TITLE
Benchmarking for Pallets

### ISSUE THREAD

**Issue by marcio-diaz** [paritytech/substrate#4876]
Issue to track progress on benchmarking dispatch calls.

In order of importance from Gav

- [x] Identity. @shawntabrizi 
- [x] Balances. @shawntabrizi 
- [x] Timestamp. @marcio-diaz  (#4891)
- [x] Polkadot/Claims. @shawntabrizi https://github.com/paritytech/polkadot/pull/876
- [x] Vesting. @marcio-diaz (#5048)
- [x] Im Online. @shawntabrizi 
- [x] Staking @shawntabrizi https://github.com/paritytech/substrate/pull/5183
- [x] Session @shawntabrizi https://github.com/paritytech/substrate/pull/5183
- [x] Elections Phragmen @kianenigma 
- [x] Democracy. @marcio-diaz (https://github.com/paritytech/substrate/pull/5257)
- [x] Collective. @marcio-diaz (https://github.com/paritytech/substrate/pull/5343)
- [x] Offences.@marcio-diaz (review #5411)
- [x] Treasury @shawntabrizi https://github.com/paritytech/substrate/pull/5287
- [x] Utility @shawntabrizi https://github.com/paritytech/substrate/pull/5384

**Comment by shawntabrizi** [comment]
Updated with order of importance from gav

**Comment by apopiak** [comment]
It seems `system` is missing from this?
