### ISSUE TITLE
Prepare for Polkadot launch and Substrate 2.0 freeze

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#4961]
On the Substrate side:
- [x] Lazy reaping: https://github.com/paritytech/substrate/pull/4895
- [x] Lazy payouts: https://github.com/paritytech/substrate/pull/4474/
- [x] Offchain Phragmen: https://github.com/paritytech/substrate/pull/4517/
- [x] Migrate storage maps: https://github.com/paritytech/substrate/issues/4917
- [x] Dispatch & block weights CC @shawntabrizi et al.
  - [x] Macro: https://github.com/paritytech/substrate/pull/4962
  - [x] Pallets: https://github.com/paritytech/substrate/issues/4876
  - [x] `on_initialize`/`on_finalize`
  - [x] Root calculation with extrinsic benchmarks. https://github.com/paritytech/substrate/pull/5035
  - [x] Root calculation (amortized). 
  - [x] Rest of block execution init/teardown in executive.
  - [x] Combine benchmark timing and complexity analysis to derive weight predictors (https://github.com/paritytech/substrate/pull/5288).
  - [x] Create sufficiently accurate weight formula, based solely on call data (not on state!), refactoring dispatches as necessary.
  - [x] Implement weights through all pallets (`FunctionOf`) (tracking issue: #5596).
- [x] Assign unique storage names to pallets: https://github.com/paritytech/substrate/pull/5010
- Stability
  - [x] Memory leaks (https://github.com/paritytech/substrate/issues/5106, #5608)
  - [x] Network connections leaks (https://github.com/paritytech/substrate/issues/4679, #5278)
  - [x] Threading issues & deadlocks (#5647, #5725 )
- [x] Refactor democracy away from batch processing (https://github.com/paritytech/substrate/issues/5248)
- [x] Fix prime member selection (https://github.com/paritytech/substrate/issues/5290)

On the Polkadot side:
- [x] Corresponding PR for #4895 and #4820: https://github.com/paritytech/polkadot/pull/834
- [x] Upgrade/migrate Kusama with that ^^^
- [x] Corresponding PR for #4917.
- [x] Upgrade/migrate Kusama with the corresponding PR for #4917

**Comment by kianenigma** [comment]
IMO this is also worth fixing https://github.com/paritytech/substrate/issues/2494

**Comment by gavofyork** [comment]
That's very much on-trivial and there may be no good solution. Until we have a solution that works with staking being off-chain, then I would leave it.

**Comment by JoshOrndorff** [comment]
> Create sufficiently accurate weight formula, based solely on call data (not on state!), refactoring dispatches as necessary.

A few months ago I came up with this pattern where the weight of a call seems like it shold depend on state. The caller passes the expected value of the state, the weight is calculated based on that expected value, and the call `ensure`s that the passed value is accurate.

https://github.com/substrate-developer-hub/recipes/blob/fc4c625addf43cb5088a73f6f0559db24fc2bd95/pallets/weights/src/lib.rs#L144-L149
