### ISSUE TITLE
tracking: Moving node-* tooling into client and generalize it

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#6001]
We have a few crates/features in `/bin/node/` that are useful for non-node substrate chains as well. We should generalize them and move them over to client for easier reuse.

Namely these are:

- [ ] `node/bench`
- [ ] `node/inspect`
- [ ] `node/cli/browser-demo` && `node/browser-testing`
- [ ] `utils/chain-spec-builder`
- [ ] `node/testing/src/bench.rs`
