### ISSUE TITLE
Post Weights Checklist

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#6040]
Here are some things that we should do once initial weights are "completed" (see https://github.com/paritytech/substrate/issues/5596)

- [ ] Write down all changed APIs to pallets (additional parameters, additional traits, etc)

- [ ] Write down all changed functionality to pallets (new functions? functions do different things?)

- [ ] Write down all assumptions about maximums taken in weight calculations.

- [x] Double check all weights one last time (sanity check)

 - [ ] Ensure Polkadot JS API is updated for changed APIs and Functionality

- [ ] Check operational dispatches if they should be operational, and check if any new dispatches can be operational.

- [x] Make sure we can save a blockchain with full blocks using only operational transactions. (https://github.com/paritytech/substrate/pull/6089)

**Comment by joepetrowski** [comment]
- [ ] Fee calculation from block data: https://github.com/paritytech/substrate/issues/6022

**Comment by kianenigma** [comment]
- [ ] move all weights to `saturating_xxx`.

**Comment by apopiak** [comment]
+ [ ] collect open questions regarding future weight work (e.g. "how to do transitive weights well?", "how to help others building with substrate to do weights well?")

**Comment by thiolliere** [comment]
> move all weights to saturating_xxx.

an option could also be to use a type which saturate by itself, std provides, https://doc.rust-lang.org/core/num/struct.Wrapping.html
Somebody implemented https://crates.io/crates/saturating
Though I think manual saturation is fine.
