### ISSUE TITLE
Seal: Deployment Tracking Issue

### ISSUE THREAD

**Issue by athei** [paritytech/substrate#6357]
We want to get the contracts module ready for deployment soonish. Here we track what is absolutely necessary before doing so. I expect that these should be mainly security and API issues. Please feel free to discuss below.

- [x] Storage Transactions in order to greatly simplify implementation and subsequently creation of a sane weight schedule (https://github.com/paritytech/substrate/pull/6269 https://github.com/paritytech/substrate/pull/6382)
- [x] API rework. We need to get the API right before deployment. (https://github.com/paritytech/substrate/issues/6355 https://github.com/paritytech/substrate/issues/5513)
- [ ] Secure weights: That means working out a weight schedule that secures the module against DoS. The current values are provisional and must be replaced by values that are backed up by benchmarks.
- [ ] Use proper weight for balance transfers (https://github.com/paritytech/substrate/issues/4713)
- [ ] Audit allocator usage (https://github.com/paritytech/substrate/issues/5379)
- [ ] Lazy contract removal (#6594)
- [ ] Storage rent for code (#6596)

**Comment by athei** [comment]
The issues open for deployment are now tracked in a separate column inside the [contracts project](https://github.com/paritytech/substrate/projects/6).
