### ISSUE TITLE
seal: Add secure weights

### ISSUE THREAD

**Issue by athei** [paritytech/substrate#6717]
Currently, the weights used in the `Schedule` are placeholder values that are just based on guesswork. We need to replace them with proper values determined by benchmarks.

In order to do that we use the benchmarking system used by the rest of substrate. This allows us to have those values automatically determined for each runtime and on each change to the contracts module.

- [x] Add weights for dispatchables (#6715)
- [x] Add weights or API calls (#7017)
- [x] Add weights for wasm instructions (#7361)

**Comment by athei** [comment]
The gas `Schedule` can now be generated completely automated for every runtime that uses pallet contracts.
