### ISSUE TITLE
Releasing 2.0 final tracking issue

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#6865]
We've successfully pushed Polkadot and throughout the release candidates integrated changes and fixes, it is time to commit and work towards the final release. This is the tracking issue in which we have an overview of all that is still to be done and required before we can make that move. Edit as necessary.

List of known issues to be fixed, before we can release:

 - [x] Move to upstream wasmtime (PR: https://github.com/paritytech/substrate/pull/6759)
 - [x] Fully Automated Benchmarking (https://github.com/paritytech/substrate/issues/6168)
 - [x] [Updating weight info for phragem](https://github.com/paritytech/substrate/pull/7161)
 - [x] Restore old subkey behavior (https://github.com/paritytech/substrate/issues/7008)
 - [ ] ~~Async Keystore (https://github.com/paritytech/substrate/issues/7000)~~
 - [x] awaiting for companion to complete https://github.com/paritytech/polkadot/pull/1743
 - [ ] [u32 refcounts](https://github.com/paritytech/substrate/pull/7164)
 - [x] [allow pallets to have fixed index](https://github.com/paritytech/substrate/pull/6969)

Process and decision to be done:
- [ ] ~~Unified Pallet Storage Versioning (https://github.com/paritytech/substrate/issues/6888)~~
- [ ] [Continuous releasing framework](https://github.com/gnunicorn/cargo-unleash/issues/15)

**Comment by thiolliere** [comment]
maybe we also want this one https://github.com/paritytech/substrate/issues/6280

**Comment by apopiak** [comment]
We will want some story of how to migrate to 2.0 (this will likely just be some documentation about how to do it manually).

We will also want some canonical way of storing the storage version of a pallet so that everyone building on Substrate 2.0 works from the same base and we can make future migrations easier.
