### ISSUE TITLE
Rearrange repo

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#717]
Repo is currently a bit of a mess from the Polkadot days. With version 1.0 coming up, it's time to get things in shape.

# Phase 1

New top-level structure should reflect the different "levels" of Substrate:
  - [x] `/core`: The core Substrate components. This is code that is common across all Substrate chains. #719
  - [x] `/srml`: The Substrate Runtime Module Library (SRML, pronounced "surmul"). This is our primary framework for writing runtimes in Substrate. Substrate chains can exist perfectly well without reference to this code, but many will use it.
  - [x] `/node`: The Substrate Node application. This is code specific to the generalised Substrate node. It will likely sync most substrate chains, but its block-authoring capacity will be limited to chains whose runtime supports this block-authoring version, pretty much a subset of those built with SRML. #719
  - [x] Miscellanea (`safe-mix`, `subkey`, `environmental`, `parity-codec` (was `codec`), `pwasm-libc`, `pwasm-alloc`). Smaller, independent projects that will eventually move to their own repo should be moved to the top-level. #719

There are some things that muddy the water a little and will need to be refactored.
- [x] `substrate-runtime-primitives` is mostly code that belongs under `core`. However there are small parts, in `generic` and `tests`, which use the `substrate-runtime-support` crate (for `Dispatchable` trait), which is not `core`. This requirement should be purged and the module should be moved to become `sr-primitives` (see next). #719 
- [x] Several other modules have phantom dependencies on `substrate-runtime-support`; this dependency should be removed:
  - [x] `bft`
  - [x] `client/db`
  - [x] `runtime-version`
  - [x] `consensus`
  - [x] `executor`
- [x] `client` module depends on `JsonMetadata`, as defined in `substrate-runtime-support` (a design oversight, to be addressed in #721). Shared code/tests should be removed to a shared crate until #721 is addressed.
- [x] `substrate-runtime-io`, `substrate-runtime-std`, `substrate-runtime-sandbox`, `substrate-runtime-primitives` and `substrate-runtime-version` are independent of the SRML and should be renamed to `sr-io`, `sr-std`, `sr-sandbox`, `sr-primitives` and `sr-version`. All other modules matching `substrate-runtime-*` should be renamed to `srml-*`.
- [x] `ed25519`: Merge into `substrate-primitives` (it is dependent on it anyway) #719

# Phase 2

Certain crates should be removed from `core`, either by merging or splitting out into separate repos:
- [ ] `environmental`: Split out into own repo.
- [x] `parity-codec`: Split into own repo.
- [x] `safe-mix`: Split into own repo.
- [x] `pwasm-alloc`, `pwasm-libc`: Merge into `sr-std`.
