### ISSUE TITLE
Roadmap for allowing browser-embedded nodes to connect to Substrate networks

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#7467]
- [ ] Make it possible for node operators to attach a TLS certificate to their libp2p WebSocket server. I believe this can be done by adding a CLI option that passes a certificate.

- [ ] Add a WebRTC "client" in nodes.

- [ ] Implement some mechanism for nodes to relay WebRTC SDPs, in other words to act as signalling servers. This point is quite vague and needs more thoughts.

**Comment by tomaka** [comment]
cc https://github.com/libp2p/rust-libp2p/issues/1066

**Comment by tomaka** [comment]
> Make it possible for node operators to attach a TLS certificate to their libp2p WebSocket server. I believe this can be done by adding a CLI option that passes a certificate.

I put that item here because it believe that it isn't super hard to implement.
However, it might be easier to just ask people to put a reverse proxy with a certificate in front of the WebSocket endpoint.

**Comment by MichaelMackus** [comment]
For the first bullet point, a "quick fix" could be to use a reverse proxy (like nginx or something) that handles the SSL cert. Would definitely be nice to support within the libp2p library, though.

**Comment by MichaelMackus** [comment]
> > Make it possible for node operators to attach a TLS certificate to their libp2p WebSocket server. I believe this can be done by adding a CLI option that passes a certificate.
> 
> I put that item here because it believe that it isn't super hard to implement.
> However, it might be easier to just ask people to put a reverse proxy with a certificate in front of the WebSocket endpoint.

You could also do what js-libp2p does in their docs for the webrtc-star server, and provide a docker-compose file to automatically setup the reverse proxy. The nice thing is this way letsencrypt can be automated with this as well.

**Comment by expenses** [comment]
>  However, it might be easier to just ask people to put a reverse proxy with a certificate in front of the WebSocket endpoint.

We're already doing this for parity nodes, so this is probably the way to go instead of modifying the client.

**Comment by tomaka** [comment]
Since this issue has been opened, we realized that in the context of a browser extension, non-secure WebSockets worked.

Therefore, another thing that can be considered is that nodes that nodes all listen through the WebSocket protocol by default, unless for example they were started using `--validator`.

**Comment by tomaka** [comment]
Issue still relevant and important.

**Comment by tomaka** [comment]
cc https://github.com/libp2p/specs/issues/220

**Comment by tomaka** [comment]
https://github.com/ipfs/js-ipfs/issues/611 seems like a big problem.

**Comment by tomaka** [comment]
Progress is done here:
https://github.com/libp2p/rust-libp2p/pull/2622
https://github.com/libp2p/specs/pull/412

**Comment by tomaka** [comment]
Would be closed by https://github.com/paritytech/substrate/pull/12529
