### ISSUE TITLE
Move as much code out of node into core as possible

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#750]
This a meta-issue. Offenders:

- [ ] `node_consensus`: Should be removed to `core`.
- [ ] `node_network`: Should be removed to `core`.
- [x] ~`node_transaction_pool`: A general, runtime-pluggable transaction queue as in #728 should allow this to be eliminated.~
- [x] ~`node_api`: The `pub mod api { impl_stubs!( ... ) }` should be able to be reused for creating an ergonomic calling interface in native code, thereby eliminating the need for most of the API boilerplate.~
- [ ] `node_service`: Looks pretty boilerplatey. Use macros and/or more generics in order to get it down to the essentials.
- [ ] Runtime refactorings:
  - [x] ~~#926~~
  - [ ] #920

**Comment by bkchr** [comment]
I'm started working on the consensus stuff.

**Comment by gavofyork** [comment]
@gnunicorn & @bkchr could you check with each other that your changes don't collide? :)

**Comment by bkchr** [comment]
@gavofyork I think this issue can be closed?
