### ISSUE TITLE
Migrate substrate pallets to use `pallet!`

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#7882]
Here is the list of pallet and their status, if you want to migrate one you can put your name after it to avoid duplicated work.
some help guidelines to do migration: https://crates.parity.io/frame_support/attr.pallet.html#upgrade-guidelines
some help guidelines to review a migration: https://crates.parity.io/frame_support/attr.pallet.html#checking-upgrade-guidelines

* [x] pallet-assets @dvdplm #7984 
* [x] pallet-atomic-swap @thiolliere
* [x] pallet-aura
* [x] pallet-authority-discovery
* [x] pallet-authorship
* [x]  pallet-babe @shaunxw #8310
* [x] pallet-balances @ascjones  #7936
* [x] pallet-bounties @shamb0 
* [x] pallet-collective @koushiro 
* [x] pallet-contracts
* [x] pallet-democracy
* [x] pallet-elections (no need to to migrate except asked otherwise)
* [x] pallet-elections-phragmen @kianenigma #8044 
* [x] pallet-example @thiolliere
* [x] pallet-example-offchain-worker @thiolliere
* [x] pallet-example-parallel @thiolliere
* [x] pallet-grandpa @octol https://github.com/paritytech/substrate/pull/8724
* [x] pallet-identity
* [x] pallet-im-online
* [x] pallet-indices @ascjones https://github.com/paritytech/substrate/pull/8465
* [x] pallet-lottery
* [x] pallet-membership @koushiro 
* [x] pallet-metadata
* [x] pallet-multisig
* [x] pallet-nicks
* [x] pallet-offences
* [x] pallet-proxy @emostov #8365
* [x] pallet-randomness-collective-flip
* [x] pallet-recovery
* [x] pallet-scheduler
* [x] pallet-scored-pool
* [x] pallet-session https://github.com/paritytech/substrate/pull/9796
* [x] pallet-session-historical
* [x] pallet-society
* [x] pallet-staking @kianenigma
* [x] pallet-sudo @ascjones https://github.com/paritytech/substrate/pull/8448
* [x] pallet-system @ascjones #7898
* [x] pallet-timestamp
* [x] pallet-tips @koushiro  
* [x] pallet-transaction-payment @kianenigma
* [x] pallet-treasury @shamb0 
* [x]  pallet-utility @shaunxw #8326 
* [x] pallet-vesting @shaunxw #8440
* [x] node template https://github.com/paritytech/substrate/pull/7981

**Comment by kianenigma** [comment]
> pallet-executive

Is this a mistake? 

> pallet-elections

I wouldn't migrate this one until an external team or someone asks for it tbh. It is not really maintained.

**Comment by shaunxw** [comment]
>     * [ ]  pallet-babe @shamb0
>
>     * [ ]  pallet-utility @shamb0

@thiolliere  Some mistakes here, it should be:

* [x]  pallet-babe @shaunxw #8310
* [ ]  pallet-utility @shaunxw #8326

**Comment by shawntabrizi** [comment]
Here is an issue for migrating the Polkadot pallets: https://github.com/paritytech/polkadot/issues/2882

**Comment by andresilva** [comment]
@octol will be migrating the grandpa pallet.

**Comment by shaunxw** [comment]
These pallets migration are merged and can be ticked now:
- pallet-democracy
- pallet-multisig
- pallet-scheduler

**Comment by koushiro** [comment]
I plan to continue migrating `pallet-collective` and `pallet-membership` to pallet attribute macro, is anyone working on them?

**Comment by thiolliere** [comment]
I put your name, nobody is working on it AFAIK

**Comment by apopiak** [comment]
Just a note that we want to mark the extrinsics as `pub` (instead of `pub(crate)` from now on (see this PR: https://github.com/paritytech/substrate/pull/9078).

**Comment by koushiro** [comment]
@shawntabrizi I found a issue in the process of migrating `pallet-membership` to new pallet attribute macro (#9080). The **storage prefix** and **pallet name** in the metadata generated by the new pallet macro are consistent, but for the pallets that use the instance and the old macro, `Instance+PalletName` will be used as the storage prefix. 
I saw issue #8391, but I want to know if there is a specific macro syntax to solve this problem.

<details>
  <summary>metadata generated by old macro</summary>

```json
{
  "name": "TechnicalMembership",
  "storage": {
    "prefix": "Instance1Membership",
    "entries": [
      {
        "name": "Members",
        "modifier": "Default",
        "ty": {
          "Plain": "Vec<T::AccountId>"
        },
        "default": [
          0
        ],
        "documentation": [
          " The current membership, stored as an ordered Vec."
        ]
      },
      {
        "name": "Prime",
        "modifier": "Optional",
        "ty": {
          "Plain": "T::AccountId"
        },
        "default": [
          0
        ],
        "documentation": [
          " The current prime member, if one exists."
        ]
      }
    ]
  },
  "calls": [
    {
      "name": "add_member",
      "arguments": [
        {
          "name": "who",
          "ty": "T::AccountId"
        }
      ],
      "documentation": [
        " Add a member `who` to the set.",
        "",
        " May only be called from `T::AddOrigin`."
      ]
    },
    {
      "name": "remove_member",
      "arguments": [
        {
          "name": "who",
          "ty": "T::AccountId"
        }
      ],
      "documentation": [
        " Remove a member `who` from the set.",
        "",
        " May only be called from `T::RemoveOrigin`."
      ]
    },
    {
      "name": "swap_member",
      "arguments": [
        {
          "name": "remove",
          "ty": "T::AccountId"
        },
        {
          "name": "add",
          "ty": "T::AccountId"
        }
      ],
      "documentation": [
        " Swap out one member `remove` for another `add`.",
        "",
        " May only be called from `T::SwapOrigin`.",
        "",
        " Prime membership is *not* passed from `remove` to `add`, if extant."
      ]
    },
    {
      "name": "reset_members",
      "arguments": [
        {
          "name": "members",
          "ty": "Vec<T::AccountId>"
        }
      ],
      "documentation": [
        " Change the membership to a new set, disregarding the existing membership. Be nice and",
        " pass `members` pre-sorted.",
        "",
        " May only be called from `T::ResetOrigin`."
      ]
    },
    {
      "name": "change_key",
      "arguments": [
        {
          "name": "new",
          "ty": "T::AccountId"
        }
      ],
      "documentation": [
        " Swap out the sending member for some other key `new`.",
        "",
        " May only be called from `Signed` origin of a current member.",
        "",
        " Prime membership is passed from the origin account to `new`, if extant."
      ]
    },
    {
      "name": "set_prime",
      "arguments": [
        {
          "name": "who",
          "ty": "T::AccountId"
        }
      ],
      "documentation": [
        " Set the prime member. Must be a current member.",
        "",
        " May only be called from `T::PrimeOrigin`."
      ]
    },
    {
      "name": "clear_prime",
      "arguments": [],
      "documentation": [
        " Remove the prime member if it exists.",
        "",
        " May only be called from `T::PrimeOrigin`."
      ]
    }
  ],
  "event": [
    {
      "name": "MemberAdded",
      "arguments": [],
      "documentation": [
        " The given member was added; see the transaction for who."
      ]
    },
    {
      "name": "MemberRemoved",
      "arguments": [],
      "documentation": [
        " The given member was removed; see the transaction for who."
      ]
    },
    {
      "name": "MembersSwapped",
      "arguments": [],
      "documentation": [
        " Two members were swapped; see the transaction for who."
      ]
    },
    {
      "name": "MembersReset",
      "arguments": [],
      "documentation": [
        " The membership was reset; see the transaction for who the new set is."
      ]
    },
    {
      "name": "KeyChanged",
      "arguments": [],
      "documentation": [
        " One of the members' keys changed."
      ]
    },
    {
      "name": "Dummy",
      "arguments": [
        "sp_std::marker::PhantomData<(AccountId, Event)>"
      ],
      "documentation": [
        " Phantom member, never used."
      ]
    }
  ],
  "constants": [],
  "errors": [
    {
      "name": "AlreadyMember",
      "documentation": [
        " Already a member."
      ]
    },
    {
      "name": "NotMember",
      "documentation": [
        " Not a member."
      ]
    }
  ],
  "index": 15
}
```

</details>

<details>
  <summary>metadata generated by new macro</summary>

```json
{
  "name": "TechnicalMembership",
  "storage": {
    "prefix": "TechnicalMembership",
    "entries": [
      {
        "name": "Members",
        "modifier": "Default",
        "ty": {
          "Plain": "Vec<T::AccountId>"
        },
        "default": [
          0
        ],
        "documentation": [
          " The current membership, stored as an ordered Vec."
        ]
      },
      {
        "name": "Prime",
        "modifier": "Optional",
        "ty": {
          "Plain": "T::AccountId"
        },
        "default": [
          0
        ],
        "documentation": [
          " The current prime member, if one exists."
        ]
      }
    ]
  },
  "calls": [
    {
      "name": "add_member",
      "arguments": [
        {
          "name": "who",
          "ty": "T::AccountId"
        }
      ],
      "documentation": [
        " Add a member `who` to the set.",
        "",
        " May only be called from `T::AddOrigin`."
      ]
    },
    {
      "name": "remove_member",
      "arguments": [
        {
          "name": "who",
          "ty": "T::AccountId"
        }
      ],
      "documentation": [
        " Remove a member `who` from the set.",
        "",
        " May only be called from `T::RemoveOrigin`."
      ]
    },
    {
      "name": "swap_member",
      "arguments": [
        {
          "name": "remove",
          "ty": "T::AccountId"
        },
        {
          "name": "add",
          "ty": "T::AccountId"
        }
      ],
      "documentation": [
        " Swap out one member `remove` for another `add`.",
        "",
        " May only be called from `T::SwapOrigin`.",
        "",
        " Prime membership is *not* passed from `remove` to `add`, if extant."
      ]
    },
    {
      "name": "reset_members",
      "arguments": [
        {
          "name": "members",
          "ty": "Vec<T::AccountId>"
        }
      ],
      "documentation": [
        " Change the membership to a new set, disregarding the existing membership. Be nice and",
        " pass `members` pre-sorted.",
        "",
        " May only be called from `T::ResetOrigin`."
      ]
    },
    {
      "name": "change_key",
      "arguments": [
        {
          "name": "new",
          "ty": "T::AccountId"
        }
      ],
      "documentation": [
        " Swap out the sending member for some other key `new`.",
        "",
        " May only be called from `Signed` origin of a current member.",
        "",
        " Prime membership is passed from the origin account to `new`, if extant."
      ]
    },
    {
      "name": "set_prime",
      "arguments": [
        {
          "name": "who",
          "ty": "T::AccountId"
        }
      ],
      "documentation": [
        " Set the prime member. Must be a current member.",
        "",
        " May only be called from `T::PrimeOrigin`."
      ]
    },
    {
      "name": "clear_prime",
      "arguments": [],
      "documentation": [
        " Remove the prime member if it exists.",
        "",
        " May only be called from `T::PrimeOrigin`."
      ]
    }
  ],
  "event": [
    {
      "name": "MemberAdded",
      "arguments": [],
      "documentation": [
        " The given member was added; see the transaction for who."
      ]
    },
    {
      "name": "MemberRemoved",
      "arguments": [],
      "documentation": [
        " The given member was removed; see the transaction for who."
      ]
    },
    {
      "name": "MembersSwapped",
      "arguments": [],
      "documentation": [
        " Two members were swapped; see the transaction for who."
      ]
    },
    {
      "name": "MembersReset",
      "arguments": [],
      "documentation": [
        " The membership was reset; see the transaction for who the new set is."
      ]
    },
    {
      "name": "KeyChanged",
      "arguments": [],
      "documentation": [
        " One of the members' keys changed."
      ]
    },
    {
      "name": "Dummy",
      "arguments": [
        "PhantomData<(T::AccountId,<T as Config<I>>::Event)>"
      ],
      "documentation": [
        " Phantom member, never used."
      ]
    }
  ],
  "constants": [],
  "errors": [
    {
      "name": "AlreadyMember",
      "documentation": [
        " Already a member."
      ]
    },
    {
      "name": "NotMember",
      "documentation": [
        " Not a member."
      ]
    }
  ],
  "index": 15
}
```

</details>

diff:

```
4c4
<     "prefix": "Instance1Membership",
---
>     "prefix": "TechnicalMembership",
177c177
<         "sp_std::marker::PhantomData<(AccountId, Event)>"
---
>         "PhantomData<(T::AccountId,<T as Config<I>>::Event)>"
```

**Comment by thiolliere** [comment]
> @shawntabrizi I found a issue in the process of migrating `pallet-membership` to new pallet attribute macro (#9080). The **storage prefix** and **pallet name** in the metadata, generated by the new pallet macro, are consistent, but for the pallets that use the instance and the old macro, `Instance+PalletName` will be used as the storage prefix.
> I saw issue #8391, but I want to know if there is a specific macro syntax to solve this problem.

the solution is to migrate the storages, in order to use their new pallet prefix.
The issue #8391 could help, but I don't think it is the correct way to solve it. Using the pallet name for pallet prefix is more future proof I think.

**Comment by koushiro** [comment]
@thiolliere Is it possible to cause storage conflicts? e.g. `Council` and `TechnicalCommitte` use the same pallet(`pallet-collective`), but different instances.

**Comment by OLUWAMUYIWA** [comment]
I plan to migrate pallet-society. Is anyone else working on it?

**Comment by thiolliere** [comment]
> I plan to migrate pallet-society. Is anyone else working on it?

I'm not aware of anybody working on it yet

**Comment by OLUWAMUYIWA** [comment]
Okay then. I have picked it

**Comment by thiolliere** [comment]
finally finished for substrate pallets, thanks for all contributions

**Comment by shawntabrizi** [comment]
Big thank you to everyone for this!
