### ISSUE TITLE
Storage chains: Tracking issue

### ISSUE THREAD

**Issue by arkpar** [paritytech/substrate#7962]
Substrate should support a kind of blockchain optimized for storing arbitrary data. The data would be stored not in the state trie, but rather off the chain as extrinsics. The state only contains a merkle trie root for all the block extrinsics.

- [x] Implement blockchain-pruning, so that after a certain period, transactions are thrown out from the database. (#7868)
- [x] Implement IPFS p2p protocol for substrate, so substrate could appear as an IPFS node. it would only need to index and serve transactions contained in the chain (#7963).
- [ ] Publish transactions on IPFS DHT
- [x] Storage renewal. A special kind of extrinsic that references an existing extrinsic and prevents it from being pruned.
- [ ] Offchain worker API for grabbing and/or hashing/merklising stored/indexed transactions
- [x] Write a runtime module. 
- [x] Fast/warp sync support

**Comment by arkpar** [comment]
Closing as this has reached ready status for standalone deployment.
