### ISSUE TITLE
Tracking issue for new token stuff

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#8453]
FTs:
- [ ] Implement `fungible::*` for Balances pallet.
- [ ] Introduce `fungibles::Lockable`/`fungible::Lockable` and implement for Balances pallet.
- [ ] Implement `fungibles::Unbalanced` for `Assets` pallet.
- [ ] Introduce `ReservableAssets` derivative pallet and implement `fungibles::Reserve`.
- [ ] Introduce `LockableAssets` derivative pallet and implement `fungibles::Lock`.
- [ ] Swtich over trait requirements from `Currency` to `fungible::*` in pallets.
- [ ] XCM for `can_withdraw`, `can_deposit`, `balance`, `reserved_balance`.
- [ ] Provider pallet, which allows valuable assets to be locked in exchange for a provider reference.

NFTS:
- [ ] `nonfungible::*` traits.
- [ ] UniqueAssets pallet.
- [ ] Implement `nonfungible::*` trait for existing ownership systems that allow some transferable permission (membership of TC/Council).
- [ ] Create new type of pure Proxy with single transferable owner and implement `nonfungible::*` for it.

Associated #8285

**Comment by olanod** [comment]
Perhaps something for the TODO list and more of a question to hear some ideas, would it make sense to make the `Assets` pallet instantiable? My motivation is, first that it doesn't harm and second that it makes working with unrelated groups of assets a bit more convenient and conceptually more correct, if I have a pallet depending on some `fungibles::*` that have something in common and are a subset of the potentially bigger set that the one Assets instance will store I often need some extra config in my pallet to be able to filter out assets from that bigger set. With different instances of Assets I relax more and trust the pallet will be configured with right subset of assets and just rely on the type system to do the "filtering" at compile time instead. I imagine I could also query the asset to see if it comes with some label or something in its `T::Extra` data but also seems like extra work.

**Comment by gavofyork** [comment]
I would accept a PR that did it, but the other items on the list are somewhat more pressing.

**Comment by olanod** [comment]
PR is there in case you feel like giving it a quick look in a coffee/bubble tea break 😉 https://github.com/paritytech/substrate/pull/8483

**Comment by chrisdcosta** [comment]
Can this new token stuff be optional for chains that don't want or need multi-currency support? It seems to be baked in - unless I'm missing something?

**Comment by gavofyork** [comment]
All multi-currency stuff will continue to be completely optional.

**Comment by danforbes** [comment]
I'm curious about the thoughts/plans that exist around non-fungible token standards and would like to offer my contributions if they can be of help. I am the author of [a pallet](https://github.com/danforbes/pallet-nft) that defines and implements [a `UniqueAssets` trait](https://github.com/danforbes/pallet-nft#uniqueassets-trait) and have also worked with [the ORML NFT pallet](https://github.com/open-web3-stack/open-runtime-module-library/tree/master/nft). I would like to start by creating some specifications around the key/value pairs that may exist as attributes on an NFT. What are the expectations that exist around the presence of certain attributes, the values they may take, and how those values impact the presence of other attributes and their possible values? I think it would be productive to follow an approach that is similar to/inspired by [the OpenAPI (nee Swagger) specification](https://swagger.io/specification/).

**Comment by pmensik** [comment]
I am actually really interested in this initiative as well since we are about to start the development of a [generic auction pallet](https://github.com/polkadotters/SubAuction) for different NFT implementations (we have already delivered PoC on top of the `orml-nft`). So I wonder which NFT implementation is gaining the most traction at the moment and what can we do to help the standardization process within Polkadot/Kusama ecosystem. We have created our own tracking [issue](https://github.com/polkadotters/SubAuction/issues/2) inside the project so definitely appreciate any of your thoughts!

**Comment by Swader** [comment]
I would also like to participate in the NFT specification in some way, given that RMRK (which has picked up considerable steam) is, functionality-wise, far more advanced that typical NFTs are (we have nested NFTs, on-chain emotes as price discovery and signal, reactive NFTs with conditional rendering, equip mechanics, and NFTs being governed as DAOs). If we can help somehow or contribute to the discussions around speccing all this out, we'd love to.

**Comment by iorveth** [comment]
I spotted a couple of potential issues/areas of improvement for `nonfungible`(s) traits and `uniques` pallet. 
Let me know if you are interested in further contribution, please 
https://github.com/paritytech/substrate/issues/9208,
https://github.com/paritytech/substrate/issues/9207,
https://github.com/paritytech/substrate/pull/9206

**Comment by kinosang** [comment]
do we really need a AssetsFreezer pallet? could we just implement `fungibles::Hold` in assets pallet?

**Comment by flipchan** [comment]
It would be really nice to get a freeze function that can freeze X amount of a certain asset's.  Similar to how it's doable with  "T::Currency::freeze(AccountId, Balance)?". 
I am currently manually implementing this in the LLM pallet(the freeze X amount of a certain asset, where the use case is that asset's work similar to tokens) at https://github.com/liberland/liberland_substrate . It would be great to have this built into the asset pallet, as this can then be expanded and it will allow implementations such as: Voting using pallet-democracy and the chain holding the on-chain asset's to vote with the onchain asset's instead of what's currently just a T::Currencyfreeze with pallet democracy.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/statemint-update-roadmap/1200/1
