### ISSUE TITLE
ParityDb stabilization tracking

### ISSUE THREAD

**Issue by arkpar** [paritytech/substrate#9201]
This lists all items that need to be complete to make parity-db the default backend in substrate
- [x] Implement an "auto" database backend for backward compatibility. It detects if rocksdb database already exists and uses it. Otherwise defaults to paritydb.
- [x] Finalize column settings. This includes size tier and compression settings.
- [x] Move polkadot specific storage to paritydb.
- [x] Make sure polkadot db is not using the same path as the main database. `purge-chain` should still delete both. 
- [x] Run for two week on parity validators.

**Comment by hirschenberger** [comment]
Maybe in conjunction with this PR we can get this landed https://github.com/paritytech/substrate/pull/8658
