### ISSUE TITLE
Tracking Issue for Substrate's NPoS

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#9511]
### Non-technical overview 

https://hackmd.io/wC6XTy36QsCmkfolX38Miw

# Task List 

(expect this to grow and change over time)

- [ ] Provide a type for submitting solutions into multiple pages #9442 
- [ ] Allow staking to sort its nominators in a meaningful way #9507
- [x] Staking should be able to stop iteration and pick it up later, for multi-block snapshot. #9313  
- [ ] Breaking change to election provider pallet that generates the snapshot over multiple blocks.
	- would be good to think about how we can make this fail-safe. We could fork the current pallet, let it live in the runtime, and then deploy the new one in a passive way and let it work  	 
- [ ] Generate paged version of all data types, we can only amalgamate the solution in the very last step, when we iterate something like `PagedSupports` and finally put all of the relevant exposures into storage.

**Comment by kianenigma** [comment]
Monthly update notes: https://gist.github.com/kianenigma/aa835946455b9a3f167821b9d05ba376

**Comment by kianenigma** [comment]
Almost everything needed for this work is now done and tested in my WIP branch. I've updated the main task list with 4 major steps of how this should be backported to the master branch.

**Comment by kianenigma** [comment]
about reading relay chain state from parachain: https://github.com/paritytech/cumulus/issues/320
