### ISSUE TITLE
Further Benchmarking Improvements Tracking

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#9513]
* [ ] Improve the `add_benchmark` and `list_benchmark` syntax. Maybe we implement some trait to `AllModulesWithSystem` which can automate all of that for us. cc @KiChjang @thiolliere 
* [ ] Return Err when PoV info isnt generated https://github.com/paritytech/substrate/pull/9471#discussion_r684318346
* [ ] Insert storage info for "well known keys"
* [ ] Whitelist `BlockWeight` storage item

**Comment by thiolliere** [comment]
note sure it is the best issue for tracking this. But an additional note is:
* move the declaration of benchmark in an attribute macro, so that code can be formatted using regular tools.

**Comment by shawntabrizi** [comment]
i think this is all done or covered in other issues cc @ggwpez
